id: W3CValidationLink
name: W3CValidationLink

version: 1.0
description: <__trans phrase="published entry then add W3C Validation link">
author_name: maRk
author_link: http://labs.markdiary.com/
doc_link: http://labs.markdiary.com/logs/2014/12/w3c-validation-link.html

l10n_lexicon:
    ja:
        published entry then add W3C Validation link: 公開エントリーにW3C検証リンクを追加
callbacks:
    MT::App::CMS::template_source.edit_entry: $W3CValidatonLink::W3CValidationLink::MakeLink::_hdlr_validation_link

